### ISSUE TITLE
Color attributes + Directed option

### ISSUE THREAD

**Issue by ghapereira** [informationsea/networkxxgmml#6]
Hello, I am a user of the networkxgmml package, and it is very useful in my work. Recently, I had to
put colors in my nodes programatically, i.e., not needing to color it inside Cytoscape's features. I looked at the XGMML specification and it allows that with the tag <graphics>. I tried to add color as an attribute to my nodes but networkxgmml did not support that. Then I made a small modification in my file, that allows that:

``` python
        if 'color' in attr:
            color = attr['color']
            del attr['color']
            print >>file, '  <graphics fill="{color}" />'.format(color=color)
```

Also, I noticed that the generated graph is always directed. It does not matter that much, but I believe that adding an option for that would be good for the user, so I added a parameter 'directed=1' in the XGMMLWriter function. Then, if no directed option is provided fine, the 'directed' attribute inside the <graph> tag is the same, but if the user wants an undirected one the option is provided.

Well, I hope this ideas are useful. Thank you for your work in this module.

**Comment by informationsea** [comment]
Thank you for your comment. Could you create pull request of your changes? I want to merge them.

**Comment by ghapereira** [comment]
Ok, I will do it as soon as I can!

Edit: Hi, I am unable to make the pull request, my GitHub Desktop Client is crazy about it. Can I send to you the code by other means, email for example? Thanks.

**Comment by informationsea** [comment]
My e-mail address is okamura[AT]infromationsea.info

If you are familiar with git commands, please use `git format-patch 11f70936e2e9233780ff6f91f5ea302eb571c028` to create patch. If not, just send me all codes as a zip (or tar) archive. Thanks.

**Comment by informationsea** [comment]
I merged your code and uploaded to pypi as version 0.1.6. Thank you for your contribution.
